export const ROUTES = {
  //employee  Routes
  HOME: "/",
  ME: "/me",
  INBOX: "/inbox",
  MY_TEAM: "/my-team",
  MY_FINANCES: "/my-finances",
  LOGIN: "/login",
  LOGIN_PAGE: "/",
  REGISTER: "/auth/register",
  //Profile routes
  SETTINGS: "/settings",
  HELPCENTER: "/helpcenter",
  // FAQ: "/helpcenter/faq",
  COMPANY_POLICY: "/helpcenter/company-policy",
  EMPLOYEE_POLICY: "/helpcenter/employee-policy",
  CONTACT_SUPPORT: "/helpcenter/contact-support",
  REQUESTED_LEAVES: "/requested-leaves",
  //Admin Route
  FORMS: "/forms",
  ATTACHMENT: "/attendance",
  LEAVES: "/leaves",
  LEAVES_SETTING: "/leaves-setting",
  PERFORMANCE: "/performance",
  TEAM_LEADERS: "/team-leaders",
  FAQ: "/faq",
  ABOUT: "/about",
  SHIFT_SCHEDULE: "/shift-schedule",
  ARTICLE: "/articles",
  HOMEPAGE: "/homepage",
  PROJECTS: "/banner-section",
  EMPLOYEE_SALARY: "/employee-salary",
  NEW_EMPLOYEES: "/new-employees",
  RESIGNATION: "/resignation",
  EMPLOYEE_STATUS: "/employee-status",
  POLICIES: "/policies",
  HOLIDAYS: "/holidays",
};
