export const ROUTES = {
  HOME: "/",
  ME: "/me",
  LOGIN: "/login",
  LOGIN_PAGE: "/",
  REGISTER: "/auth/register",
  SETTINGS: "/settings",
  HELP_CENTER: "/helpcenter",
  FORMS: "/forms",
  FAQ: "/faq",
  ABOUT: "/about",
  ARTICLE: "/articles",
  ARTICLE_CREATE: "/articles/create",
  ARTICLE_VIEW: "/articles/:articleId",
  ARTICLE_EDIT: "/articles/:articleId/edit",
  HOMEPAGE: "/homepage",
  PARTNER:"/partner",
  TERM_OF_SERVICE: "/term-of-service",
  PRIVACY_POLICY:"/privacy-policy",
  EMAIL:"email-templates",
  CITIES:"/cities",
  PLACES:"/places",
  PLACES_CREATE:"/places/create",
  PLACES_VIEW :"/place/:placeId",
  PLACES_EDIT :"/place/:placeId/Edit",
  COMPANIES:"/companies",
  COMPANIES_CREATE:"/companies/create",
  COMPANIES_VIEW :"/company/:companyId",
  COMPANIES_EDIT :"/company/:companyId/Edit"
};
