export const ROUTES = {
  HOME: "/",
  ME: "/me",
  LOGIN: "/login",
  LOGIN_PAGE: "/",
  REGISTER: "/auth/register",
  SETTINGS: "/settings",
  HELP_CENTER: "/helpcenter",
  FORMS: "/forms",
  FAQ: "/faq",
  ABOUT: "/about",
  ARTICLE: "/articles",
  HOMEPAGE: "/homepage",
  PARTNER: "/partner",
};
